name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # 开启手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Install CMake 3.10.2 manually
        run: |
          wget https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh
          chmod +x cmake-3.10.2-Linux-x86_64.sh
          sudo ./cmake-3.10.2-Linux-x86_64.sh --skip-license --prefix=/usr/local
          
      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        if: env.SIGNING_KEY != ''
        run: |
          echo "${{ env.SIGNING_KEY }}" | base64 -d > app/release-key.jks

      - name: Build with Gradle (assembleInrtRelease)
        run: ./gradlew assembleInrtRelease

      - name: Build with Gradle (assembleAppRelease)
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/app/release-key.jks
        run: ./gradlew assembleAppRelease

      # 分别上传不同架构的 APK
      - name: Upload Release Artifacts (Universal)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-universal-apk
          path: app/build/outputs/apk/app/release/*-universal.apk
          retention-days: 30

      - name: Upload Release Artifacts (Arm64)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-arm64-v8a-apk
          path: app/build/outputs/apk/app/release/*-arm64-v8a.apk
          retention-days: 30

      - name: Upload Release Artifacts (Armv7)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-armeabi-v7a-apk
          path: app/build/outputs/apk/app/release/*-armeabi-v7a.apk
          retention-days: 30

