name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # 开启手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Install CMake 3.10.2 manually
        run: |
          wget https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh
          chmod +x cmake-3.10.2-Linux-x86_64.sh
          sudo ./cmake-3.10.2-Linux-x86_64.sh --skip-license --prefix=/usr/local
          
      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (assembleInrtRelease)
        run: ./gradlew assembleInrtRelease

      - name: Build with Gradle (assembleAppRelease)
        run: ./gradlew assembleAppRelease

      # 签名 APK（如果配置了 Secrets）
      - name: Sign Release APK
        if: env.SIGNING_KEY != ''
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/app/release
          signingKeyBase64: ${{ env.SIGNING_KEY }}
          alias: ${{ env.ALIAS }}
          keyStorePassword: ${{ env.KEY_STORE_PASSWORD }}
          keyPassword: ${{ env.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      # 上传签名后的 APK（如果签名成功）
      - name: Upload Signed APKs
        if: ${{ steps.sign_app.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apks
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
          retention-days: 30

      # 如果没有签名，上传未签名的 APK
      - name: Upload arm64 artifacts
        if: ${{ steps.sign_app.outcome != 'success' }}
        id: upload-arm64-apk
        uses: actions/upload-artifact@v4
        with:
          name: release-arm64-apk
          path: app/build/outputs/apk/app/release/*-arm64-v8a.apk
        continue-on-error: true

      - name: Upload armv7 artifacts
        if: ${{ steps.sign_app.outcome != 'success' }}
        id: upload-armv7-apk
        uses: actions/upload-artifact@v4
        with:
          name: release-armv7-apk
          path: app/build/outputs/apk/app/release/*-v7a.apk
        continue-on-error: true

      - name: Upload universal artifacts
        if: ${{ steps.sign_app.outcome != 'success' }}
        id: upload-universal-apk
        uses: actions/upload-artifact@v4
        with:
          name: release-universal-apk
          path: app/build/outputs/apk/app/release/*-universal.apk
        continue-on-error: true
